# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_c_speech_features_base', [dirname(__file__)])
        except ImportError:
            import _c_speech_features_base
            return _c_speech_features_base
        if fp is not None:
            try:
                _mod = imp.load_module('_c_speech_features_base', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _c_speech_features_base = swig_import_helper()
    del swig_import_helper
else:
    import _c_speech_features_base
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



from c_speech_features import c_speech_features_sigproc as sigproc


def mfcc(*args):
    return _c_speech_features_base.mfcc(*args)
mfcc = _c_speech_features_base.mfcc

def fbank(*args):
    return _c_speech_features_base.fbank(*args)
fbank = _c_speech_features_base.fbank

def logfbank(*args):
    return _c_speech_features_base.logfbank(*args)
logfbank = _c_speech_features_base.logfbank

def ssc(*args):
    return _c_speech_features_base.ssc(*args)
ssc = _c_speech_features_base.ssc

def hz2mel(hz):
    return _c_speech_features_base.hz2mel(hz)
hz2mel = _c_speech_features_base.hz2mel

def mel2hz(mel):
    return _c_speech_features_base.mel2hz(mel)
mel2hz = _c_speech_features_base.mel2hz

def get_filterbanks(*args):
    return _c_speech_features_base.get_filterbanks(*args)
get_filterbanks = _c_speech_features_base.get_filterbanks

def lifter(*args):
    return _c_speech_features_base.lifter(*args)
lifter = _c_speech_features_base.lifter

def delta(feat, N):
    return _c_speech_features_base.delta(feat, N)
delta = _c_speech_features_base.delta
# This file is compatible with both classic and new-style classes.


